### ISSUE TITLE
Обновление интеграции с anilibria api

### ISSUE THREAD

**Issue by AnyGogin31** [axeinstd/AniXapp#1]
Привет, сам сейчас пишу мобильный клиент для анилибрии (в свое удовольствие). Есть более подходящий api для интеграции с анилибрией. https://anilibria.top/api/docs/v1#/ . Могу еще накинуть возможность перехода в бота анилибрии в телеграме для просмотра серий

**Comment by AnyGogin31** [comment]
Вот получается ссылка на gist где реализована создание ссылки на бота. Там надо немного изменить. Base64 использовать из `android.util` и поменять поменять ссылку с использованием tg://resolve . https://gist.github.com/AnyGogin31/b67cfec1b53287691320ca47f2f5a868

**Comment by axeinstd** [comment]
За интеграцию с ботом спасибо) А еще у меня вопрос к предложенной апишке. Что кардинально поменялось? Есть ли какая-то функционально важная часть, которой нет у стандартного API? Мне интересно, стоит ли оно того, чтобы переписывать датаклассы, запросы и само приложение ради него.

**Comment by AnyGogin31** [comment]
Конечно точно не знаю, но просто удобнее использовать с ретрофитом. Вон если что можешь взять дата классы с оригинального приложения. https://github.com/anilibria/anilibria-app/tree/feature/new-api . Я потом могу показать как это будет работать в моём клиенте.

**Comment by axeinstd** [comment]
Возможно, но лично мне немного привычнее пользоваться ктором (на http из dart и requests из python похож). Да и у меня api как у сайта их из вк, так что если найду фичу, которая мне будет прям нужна, использую предложенную апишку. В любом случае спасибо

**Comment by axeinstd** [comment]
К слову, я начал переписывать приложение на этот api. Я нашел неоспоримое преимущество - оно гораздо быстрее. Сервер отвечает гораздо быстрее, чем у нынешнего моего. Так что огромное спасибо за хорошую идею )
