### ISSUE TITLE
Краш приложения при попытке открыть профиль

### ISSUE THREAD

**Issue by AnyGogin31** [axeinstd/AniXapp#2]
Ниже я прикрепил логи. Понимаю что бета версия, но тоже по хорошему не забыть решить. Из-за непонятной истории комитов сложно понять, решено или нет.
![Screenshot_20240929-201615_Pixel Launcher.png](https://github.com/user-attachments/assets/0d51b116-9be2-4fda-a90d-8dced26dc4b0)

**Comment by axeinstd** [comment]
Я знаю, просто роута и файла для профиля я не сделал. Я забил на него сейчас, и эта версия по факту просто нерабочая. Ее даже для тестов использовать нельзя. Так что пока лучшее ее не трогать. Она даже для беты первой беты нерабочая)

**Comment by AnyGogin31** [comment]
Хорошо, не буду пока кидать проблемы бетки. Но наверное суть таких пре релизов в том, чтобы отлавливать ошибки перед нормальным релизом.
